/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `contacts`;

CREATE TABLE `contacts` (
  `contactId` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `fromUser` TEXT NOT NULL,
  `toUser` TEXT NOT NULL,
  `status` INT NOT NULL)
 ENGINE=InnoDB;

